title: Nathan Kyryk
url: nathankyryk.github.io 
description: > 
  Current senior at IU Luddy pursuing a BS in Data Science. I will be updating my portfolio below with projects that I am working on.

permalink: /:slug

favicon: "./logo.png" 

linkedin:
    username: nathankyryk 
    card: summary_large_image


remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" 
  appearance_toggle: true 
  back_home_text: "home.." 
  date_format: "%Y-%m-%d" 
  show_description: true 
  show_navbar: true 
  show_footer: false 
  show_copyright: true 
 
  show_projects: true 
  show_blog: false 
  show_old_projects: false 
  show_misc_list: false 
  show_reading_time: false 
  show_tags: false 
 
  home:
    title_projects: Portfolio
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: Old Projects

soopr:
  publish_token: "" 

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
